version: '1.0'
volumes:
  mysql-volume:
  ghost-volume:

services:
  ghost:
    build: .
    ports:
      - 2368:2368
    networks:
      - ghost
    restart: always
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: blog-user
      database__connection__password: supersecret
      database__connection__database: db
      storage__active: s3
      storage__s3__accessKeyId: <AWS Access Key>
      storage__s3__secretAccessKey: <AWS Secret Key>
      storage__s3__region: us-east-1
      storage__s3__bucket: <s3 bucket name>
      storage__s3__endpoint: <s3 endpoint>

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - ghost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: blog-user
      MYSQL_PASSWORD: supersecret

networks:
  ghost:
